### PR TITLE
Ubuntu fix

### PR DESCRIPTION
**Pull request by nurriz**

### CODE REVIEW

**Comment by raphink** [comment]
@nurriz open or close? :smile:

**Comment by nurriz** [comment]
It should be open. Don't know how I goofed this up so much. I removed the ubuntu.rb from the PR.

**Comment by raphink** [comment]
@nurriz not sure why you closed this again if you said it should be open?

**Comment by nurriz** [comment]
I started work on getting all tests to pass, introduce the new varnish repos and making it work with varnish 4.1. I'll make a PR when it's ready.

**Comment by raphink** [comment]
OK.

**Pull request closed without merging**
